/**
 * 開発者向け: この配列にオブジェクトを追加するだけで言葉を増やせます。
 * id: 一意の文字列
 * text: 表示テキスト
 * kind: noun | adj_na | conj | particle （図鑑分類・ビルダーでの並びのヒント）
 * tags: 相性計算用（隣接・位置ボーナス）
 * power: 基礎戦闘力
 * slotMask: 将来拡張用（現在は未使用）
 */
const WORD_CATALOG = [
  /* 基本・人物 */
  { id: "w001", text: "勇者", kind: "noun", tags: ["hero", "fantasy"], power: 6, slotMask: 7 },
  { id: "w002", text: "魔法使い", kind: "noun", tags: ["mage", "fantasy"], power: 5, slotMask: 7 },
  { id: "w003", text: "旅人", kind: "noun", tags: ["travel", "neutral"], power: 4, slotMask: 7 },
  { id: "w004", text: "学者", kind: "noun", tags: ["mind", "neutral"], power: 4, slotMask: 7 },
  { id: "w005", text: "職人", kind: "noun", tags: ["craft", "earth"], power: 5, slotMask: 7 },
  { id: "w006", text: "吟遊詩人", kind: "noun", tags: ["sound", "wind"], power: 4, slotMask: 7 },
  { id: "w007", text: "騎士", kind: "noun", tags: ["hero", "metal"], power: 6, slotMask: 7 },
  { id: "w008", text: "忍者", kind: "noun", tags: ["shadow", "wind"], power: 5, slotMask: 7 },
  { id: "w009", text: "商人", kind: "noun", tags: ["trade", "neutral"], power: 3, slotMask: 7 },
  { id: "w010", text: "錬金術師", kind: "noun", tags: ["mind", "fire"], power: 5, slotMask: 7 },
  /* 自然 */
  { id: "w011", text: "森", kind: "noun", tags: ["nature", "earth"], power: 4, slotMask: 7 },
  { id: "w012", text: "海", kind: "noun", tags: ["nature", "water"], power: 5, slotMask: 7 },
  { id: "w013", text: "山", kind: "noun", tags: ["nature", "earth"], power: 5, slotMask: 7 },
  { id: "w014", text: "雪", kind: "noun", tags: ["nature", "ice"], power: 4, slotMask: 7 },
  { id: "w015", text: "雷", kind: "noun", tags: ["nature", "thunder"], power: 6, slotMask: 7 },
  { id: "w016", text: "風", kind: "noun", tags: ["nature", "wind"], power: 5, slotMask: 7 },
  { id: "w017", text: "砂漠", kind: "noun", tags: ["nature", "earth"], power: 4, slotMask: 7 },
  { id: "w018", text: "泉", kind: "noun", tags: ["nature", "water"], power: 3, slotMask: 7 },
  { id: "w019", text: "夜空", kind: "noun", tags: ["nature", "cosmos"], power: 5, slotMask: 7 },
  { id: "w020", text: "花畑", kind: "noun", tags: ["nature", "life"], power: 3, slotMask: 7 },
  /* 抽象・概念 */
  { id: "w021", text: "希望", kind: "noun", tags: ["light", "mind"], power: 4, slotMask: 7 },
  { id: "w022", text: "記憶", kind: "noun", tags: ["mind", "shadow"], power: 4, slotMask: 7 },
  { id: "w023", text: "夢", kind: "noun", tags: ["mind", "cosmos"], power: 3, slotMask: 7 },
  { id: "w024", text: "運命", kind: "noun", tags: ["cosmos", "neutral"], power: 5, slotMask: 7 },
  { id: "w025", text: "真実", kind: "noun", tags: ["light", "mind"], power: 5, slotMask: 7 },
  { id: "w026", text: "嘘", kind: "noun", tags: ["shadow", "mind"], power: 3, slotMask: 7 },
  { id: "w027", text: "約束", kind: "noun", tags: ["light", "neutral"], power: 4, slotMask: 7 },
  { id: "w028", text: "冒険", kind: "noun", tags: ["hero", "wind"], power: 5, slotMask: 7 },
  { id: "w029", text: "静寂", kind: "noun", tags: ["ice", "mind"], power: 4, slotMask: 7 },
  { id: "w030", text: "歯車", kind: "noun", tags: ["metal", "craft"], power: 3, slotMask: 7 },
  /* 形容（〜な） */
  { id: "w031", text: "勇敢", kind: "adj_na", tags: ["hero", "fire"], power: 5, slotMask: 4 },
  { id: "w032", text: "冷静", kind: "adj_na", tags: ["ice", "mind"], power: 4, slotMask: 4 },
  { id: "w033", text: "愉快", kind: "adj_na", tags: ["sound", "light"], power: 3, slotMask: 4 },
  { id: "w034", text: "慎重", kind: "adj_na", tags: ["earth", "mind"], power: 4, slotMask: 4 },
  { id: "w035", text: "華麗", kind: "adj_na", tags: ["light", "wind"], power: 4, slotMask: 4 },
  { id: "w036", text: "謎めいた", kind: "adj_na", tags: ["shadow", "cosmos"], power: 4, slotMask: 4 },
  { id: "w037", text: "頑固", kind: "adj_na", tags: ["earth", "metal"], power: 3, slotMask: 4 },
  { id: "w038", text: "自由", kind: "adj_na", tags: ["wind", "neutral"], power: 4, slotMask: 4 },
  { id: "w039", text: "真っ直ぐ", kind: "adj_na", tags: ["light", "hero"], power: 4, slotMask: 4 },
  { id: "w040", text: "怠惰", kind: "adj_na", tags: ["shadow", "neutral"], power: 2, slotMask: 4 },
  /* 接続・助詞系（テンプレ外のつなぎ用） */
  { id: "w041", text: "そして", kind: "conj", tags: ["neutral", "link"], power: 1, slotMask: 7 },
  { id: "w042", text: "あるいは", kind: "conj", tags: ["neutral", "link"], power: 1, slotMask: 7 },
  { id: "w043", text: "しかし", kind: "conj", tags: ["shadow", "link"], power: 1, slotMask: 7 },
  { id: "w044", text: "だから", kind: "conj", tags: ["fire", "link"], power: 1, slotMask: 7 },
  { id: "w045", text: "それでも", kind: "conj", tags: ["hero", "link"], power: 1, slotMask: 7 },
  { id: "w046", text: "もしも", kind: "conj", tags: ["cosmos", "link"], power: 1, slotMask: 7 },
  { id: "w047", text: "なおかつ", kind: "conj", tags: ["mind", "link"], power: 1, slotMask: 7 },
  { id: "w048", text: "ちなみに", kind: "conj", tags: ["sound", "link"], power: 1, slotMask: 7 },
  { id: "w049", text: "ついでに", kind: "conj", tags: ["wind", "link"], power: 1, slotMask: 7 },
  { id: "w050", text: "要するに", kind: "conj", tags: ["mind", "link"], power: 1, slotMask: 7 },
  { id: "w051", text: "の", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w052", text: "で", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w053", text: "と", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w054", text: "が", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w055", text: "を", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  /* 追加名詞ブロック（拡張しやすいよう連番） */
  { id: "w056", text: "古城", kind: "noun", tags: ["shadow", "earth"], power: 4, slotMask: 7 },
  { id: "w057", text: "図書館", kind: "noun", tags: ["mind", "neutral"], power: 3, slotMask: 7 },
  { id: "w058", text: "工房", kind: "noun", tags: ["craft", "fire"], power: 4, slotMask: 7 },
  { id: "w059", text: "祭り", kind: "noun", tags: ["sound", "light"], power: 4, slotMask: 7 },
  { id: "w060", text: "迷宮", kind: "noun", tags: ["shadow", "earth"], power: 5, slotMask: 7 },
  { id: "w061", text: "星屑", kind: "noun", tags: ["cosmos", "light"], power: 5, slotMask: 7 },
  { id: "w062", text: "時計", kind: "noun", tags: ["metal", "cosmos"], power: 3, slotMask: 7 },
  { id: "w063", text: "羅針盤", kind: "noun", tags: ["wind", "mind"], power: 3, slotMask: 7 },
  { id: "w064", text: "契約", kind: "noun", tags: ["shadow", "neutral"], power: 4, slotMask: 7 },
  { id: "w065", text: "祝福", kind: "noun", tags: ["light", "life"], power: 4, slotMask: 7 },
  { id: "w066", text: "呪い", kind: "noun", tags: ["shadow", "ice"], power: 5, slotMask: 7 },
  { id: "w067", text: "剣", kind: "noun", tags: ["metal", "hero"], power: 5, slotMask: 7 },
  { id: "w068", text: "盾", kind: "noun", tags: ["metal", "earth"], power: 4, slotMask: 7 },
  { id: "w069", text: "弓", kind: "noun", tags: ["wind", "craft"], power: 4, slotMask: 7 },
  { id: "w070", text: "杖", kind: "noun", tags: ["mage", "cosmos"], power: 4, slotMask: 7 },
  { id: "w071", text: "薬草", kind: "noun", tags: ["life", "earth"], power: 3, slotMask: 7 },
  { id: "w072", text: "宝石", kind: "noun", tags: ["light", "earth"], power: 4, slotMask: 7 },
  { id: "w073", text: "地図", kind: "noun", tags: ["mind", "wind"], power: 3, slotMask: 7 },
  { id: "w074", text: "手紙", kind: "noun", tags: ["sound", "light"], power: 2, slotMask: 7 },
  { id: "w075", text: "鍵", kind: "noun", tags: ["metal", "shadow"], power: 3, slotMask: 7 },
  { id: "w076", text: "扉", kind: "noun", tags: ["shadow", "neutral"], power: 3, slotMask: 7 },
  { id: "w077", text: "灯り", kind: "noun", tags: ["light", "fire"], power: 3, slotMask: 7 },
  { id: "w078", text: "影", kind: "noun", tags: ["shadow", "neutral"], power: 4, slotMask: 7 },
  { id: "w079", text: "嵐", kind: "noun", tags: ["wind", "water"], power: 6, slotMask: 7 },
  { id: "w080", text: "虹", kind: "noun", tags: ["light", "water"], power: 3, slotMask: 7 },
  { id: "w081", text: "朝焼け", kind: "noun", tags: ["light", "fire"], power: 4, slotMask: 7 },
  { id: "w082", text: "夕暮れ", kind: "noun", tags: ["neutral", "light"], power: 3, slotMask: 7 },
  { id: "w083", text: "月明かり", kind: "noun", tags: ["cosmos", "ice"], power: 4, slotMask: 7 },
  { id: "w084", text: "猫", kind: "noun", tags: ["life", "shadow"], power: 3, slotMask: 7 },
  { id: "w085", text: "狼", kind: "noun", tags: ["life", "wind"], power: 5, slotMask: 7 },
  { id: "w086", text: "龍", kind: "noun", tags: ["fantasy", "fire"], power: 8, slotMask: 7 },
  { id: "w087", text: "妖精", kind: "noun", tags: ["life", "wind"], power: 4, slotMask: 7 },
  { id: "w088", text: "幽霊", kind: "noun", tags: ["shadow", "ice"], power: 4, slotMask: 7 },
  { id: "w089", text: "ゴーレム", kind: "noun", tags: ["earth", "metal"], power: 6, slotMask: 7 },
  { id: "w090", text: "スライム", kind: "noun", tags: ["water", "life"], power: 2, slotMask: 7 },
  { id: "w091", text: "機械", kind: "noun", tags: ["metal", "mind"], power: 5, slotMask: 7 },
  { id: "w092", text: "歌", kind: "noun", tags: ["sound", "light"], power: 3, slotMask: 7 },
  { id: "w093", text: "踊り", kind: "noun", tags: ["sound", "wind"], power: 3, slotMask: 7 },
  { id: "w094", text: "料理", kind: "noun", tags: ["life", "fire"], power: 3, slotMask: 7 },
  { id: "w095", text: "茶", kind: "noun", tags: ["life", "earth"], power: 2, slotMask: 7 },
  { id: "w096", text: "勝利", kind: "noun", tags: ["hero", "light"], power: 5, slotMask: 7 },
  { id: "w097", text: "敗北", kind: "noun", tags: ["shadow", "neutral"], power: 2, slotMask: 7 },
  { id: "w098", text: "勝負", kind: "noun", tags: ["hero", "neutral"], power: 4, slotMask: 7 },
  { id: "w099", text: "友情", kind: "noun", tags: ["light", "life"], power: 4, slotMask: 7 },
  { id: "w100", text: "宿敵", kind: "noun", tags: ["shadow", "hero"], power: 5, slotMask: 7 },
  { id: "w101", text: "守り人", kind: "noun", tags: ["hero", "earth"], power: 5, slotMask: 7 },
  { id: "w102", text: "番人", kind: "noun", tags: ["neutral", "shadow"], power: 4, slotMask: 7 },
  { id: "w103", text: "予言", kind: "noun", tags: ["cosmos", "mind"], power: 4, slotMask: 7 },
  { id: "w104", text: "代償", kind: "noun", tags: ["shadow", "neutral"], power: 3, slotMask: 7 },
  { id: "w105", text: "奇跡", kind: "noun", tags: ["light", "cosmos"], power: 6, slotMask: 7 },
  { id: "w106", text: "日常", kind: "noun", tags: ["neutral", "life"], power: 2, slotMask: 7 },
  { id: "w107", text: "非日常", kind: "noun", tags: ["cosmos", "wind"], power: 4, slotMask: 7 },
  { id: "w108", text: "境界線", kind: "noun", tags: ["mind", "shadow"], power: 4, slotMask: 7 },
  { id: "w109", text: "羅針", kind: "noun", tags: ["wind", "metal"], power: 3, slotMask: 7 },
  { id: "w110", text: "灯台", kind: "noun", tags: ["light", "water"], power: 4, slotMask: 7 },
  { id: "w111", text: "深淵", kind: "noun", tags: ["shadow", "water"], power: 6, slotMask: 7 },
  { id: "w112", text: "天空", kind: "noun", tags: ["wind", "cosmos"], power: 5, slotMask: 7 },
  { id: "w113", text: "大地", kind: "noun", tags: ["earth", "life"], power: 5, slotMask: 7 },
  { id: "w114", text: "蒼", kind: "adj_na", tags: ["water", "ice"], power: 3, slotMask: 4 },
  { id: "w115", text: "灼熱", kind: "adj_na", tags: ["fire", "light"], power: 5, slotMask: 4 },
  { id: "w116", text: "古びた", kind: "adj_na", tags: ["earth", "shadow"], power: 3, slotMask: 4 },
  { id: "w117", text: "煌めく", kind: "adj_na", tags: ["light", "cosmos"], power: 4, slotMask: 4 },
  { id: "w118", text: "眠たげ", kind: "adj_na", tags: ["neutral", "life"], power: 2, slotMask: 4 },
  { id: "w119", text: "無慈悲", kind: "adj_na", tags: ["shadow", "ice"], power: 5, slotMask: 4 },
  { id: "w120", text: "温和", kind: "adj_na", tags: ["life", "water"], power: 3, slotMask: 4 },
  { id: "w121", text: "な", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w122", text: "道端", kind: "noun", tags: ["travel", "earth"], power: 2, slotMask: 7 },
  { id: "w123", text: "石碑", kind: "noun", tags: ["earth", "shadow"], power: 3, slotMask: 7 },
  { id: "w124", text: "酒", kind: "noun", tags: ["life", "fire"], power: 3, slotMask: 7 },
  { id: "w125", text: "麦", kind: "noun", tags: ["life", "earth"], power: 2, slotMask: 7 },
  { id: "w126", text: "帆", kind: "noun", tags: ["wind", "water"], power: 3, slotMask: 7 },
  { id: "w127", text: "港", kind: "noun", tags: ["water", "trade"], power: 4, slotMask: 7 },
  { id: "w128", text: "教会", kind: "noun", tags: ["light", "neutral"], power: 3, slotMask: 7 },
  { id: "w129", text: "井戸", kind: "noun", tags: ["water", "earth"], power: 2, slotMask: 7 },
  { id: "w130", text: "鏡", kind: "noun", tags: ["light", "mind"], power: 3, slotMask: 7 },
  { id: "w131", text: "冠", kind: "noun", tags: ["light", "metal"], power: 4, slotMask: 7 },
  { id: "w132", text: "砂時計", kind: "noun", tags: ["cosmos", "earth"], power: 3, slotMask: 7 },
  { id: "w133", text: "羊皮紙", kind: "noun", tags: ["mind", "craft"], power: 2, slotMask: 7 },
  { id: "w134", text: "燭台", kind: "noun", tags: ["fire", "light"], power: 2, slotMask: 7 },
  { id: "w135", text: "革袋", kind: "noun", tags: ["travel", "craft"], power: 2, slotMask: 7 },
  { id: "w136", text: "碑文", kind: "noun", tags: ["earth", "mind"], power: 3, slotMask: 7 },
  { id: "w137", text: "種火", kind: "noun", tags: ["fire", "life"], power: 2, slotMask: 7 },
  { id: "w138", text: "旅路", kind: "noun", tags: ["travel", "wind"], power: 3, slotMask: 7 },
  { id: "w139", text: "牢獄", kind: "noun", tags: ["shadow", "metal"], power: 4, slotMask: 7 },
  { id: "w140", text: "財宝", kind: "noun", tags: ["light", "trade"], power: 4, slotMask: 7 },
  { id: "w141", text: "遺跡", kind: "noun", tags: ["earth", "shadow"], power: 4, slotMask: 7 },
  { id: "w142", text: "瀑布", kind: "noun", tags: ["water", "nature"], power: 5, slotMask: 7 },
  { id: "w143", text: "洞窟", kind: "noun", tags: ["earth", "shadow"], power: 3, slotMask: 7 },
  { id: "w144", text: "苔", kind: "noun", tags: ["life", "water"], power: 2, slotMask: 7 },
  { id: "w145", text: "竹林", kind: "noun", tags: ["nature", "wind"], power: 3, slotMask: 7 },
  { id: "w146", text: "桜吹雪", kind: "noun", tags: ["nature", "wind"], power: 3, slotMask: 7 },
  { id: "w147", text: "梅林", kind: "noun", tags: ["life", "nature"], power: 3, slotMask: 7 },
  { id: "w148", text: "火山口", kind: "noun", tags: ["fire", "earth"], power: 6, slotMask: 7 },
  { id: "w149", text: "溶岩", kind: "noun", tags: ["fire", "earth"], power: 5, slotMask: 7 },
  { id: "w150", text: "水晶", kind: "noun", tags: ["ice", "light"], power: 4, slotMask: 7 },
  { id: "w151", text: "雲海", kind: "noun", tags: ["wind", "water"], power: 4, slotMask: 7 },
  { id: "w152", text: "流星", kind: "noun", tags: ["cosmos", "fire"], power: 5, slotMask: 7 },
  { id: "w153", text: "彗星", kind: "noun", tags: ["cosmos", "ice"], power: 5, slotMask: 7 },
  { id: "w154", text: "銀河", kind: "noun", tags: ["cosmos", "light"], power: 6, slotMask: 7 },
  { id: "w155", text: "石橋", kind: "noun", tags: ["earth", "neutral"], power: 3, slotMask: 7 },
  { id: "w156", text: "木漏れ日", kind: "noun", tags: ["light", "life"], power: 3, slotMask: 7 },
  { id: "w157", text: "琥珀", kind: "noun", tags: ["earth", "light"], power: 3, slotMask: 7 },
  { id: "w158", text: "瑠璃", kind: "noun", tags: ["water", "light"], power: 3, slotMask: 7 },
  { id: "w159", text: "鉄枷", kind: "noun", tags: ["metal", "shadow"], power: 4, slotMask: 7 },
  { id: "w160", text: "銅鑼", kind: "noun", tags: ["sound", "metal"], power: 3, slotMask: 7 },
  { id: "w161", text: "硝子", kind: "noun", tags: ["light", "craft"], power: 2, slotMask: 7 },
  { id: "w162", text: "絹", kind: "noun", tags: ["craft", "light"], power: 2, slotMask: 7 },
  { id: "w163", text: "革靴", kind: "noun", tags: ["travel", "earth"], power: 2, slotMask: 7 },
  { id: "w164", text: "兜巾", kind: "noun", tags: ["hero", "shadow"], power: 3, slotMask: 7 },
  { id: "w165", text: "指輪", kind: "noun", tags: ["light", "neutral"], power: 3, slotMask: 7 },
  { id: "w166", text: "護符", kind: "noun", tags: ["light", "life"], power: 3, slotMask: 7 },
  { id: "w167", text: "香炉", kind: "noun", tags: ["fire", "mind"], power: 2, slotMask: 7 },
  { id: "w168", text: "蒸気", kind: "noun", tags: ["fire", "water"], power: 4, slotMask: 7 },
  { id: "w169", text: "レンズ", kind: "noun", tags: ["mind", "light"], power: 3, slotMask: 7 },
  { id: "w170", text: "蜜", kind: "noun", tags: ["life", "light"], power: 2, slotMask: 7 },
  { id: "w171", text: "蛾", kind: "noun", tags: ["life", "shadow"], power: 2, slotMask: 7 },
  { id: "w172", text: "蝶", kind: "noun", tags: ["life", "wind"], power: 2, slotMask: 7 },
  { id: "w173", text: "梟", kind: "noun", tags: ["shadow", "life"], power: 3, slotMask: 7 },
  { id: "w174", text: "烏", kind: "noun", tags: ["shadow", "wind"], power: 3, slotMask: 7 },
  { id: "w175", text: "鷹", kind: "noun", tags: ["wind", "hero"], power: 4, slotMask: 7 },
  { id: "w176", text: "鹿", kind: "noun", tags: ["life", "nature"], power: 3, slotMask: 7 },
  { id: "w177", text: "狐", kind: "noun", tags: ["shadow", "life"], power: 3, slotMask: 7 },
  { id: "w178", text: "兎", kind: "noun", tags: ["life", "neutral"], power: 2, slotMask: 7 },
  { id: "w179", text: "鯉", kind: "noun", tags: ["water", "life"], power: 3, slotMask: 7 },
  { id: "w180", text: "貝殻", kind: "noun", tags: ["water", "life"], power: 2, slotMask: 7 },
  { id: "w181", text: "珊瑚", kind: "noun", tags: ["water", "life"], power: 3, slotMask: 7 },
  { id: "w182", text: "藻", kind: "noun", tags: ["water", "life"], power: 2, slotMask: 7 },
  { id: "w183", text: "渦潮", kind: "noun", tags: ["water", "wind"], power: 5, slotMask: 7 },
  { id: "w184", text: "氷柱", kind: "noun", tags: ["ice", "nature"], power: 4, slotMask: 7 },
  { id: "w185", text: "雪原", kind: "noun", tags: ["ice", "nature"], power: 4, slotMask: 7 },
  { id: "w186", text: "霧雨", kind: "noun", tags: ["water", "neutral"], power: 3, slotMask: 7 },
  { id: "w187", text: "稲妻", kind: "noun", tags: ["thunder", "light"], power: 5, slotMask: 7 },
  { id: "w188", text: "極光", kind: "noun", tags: ["cosmos", "ice"], power: 5, slotMask: 7 },
  { id: "w189", text: "真夜中", kind: "noun", tags: ["cosmos", "shadow"], power: 3, slotMask: 7 },
  { id: "w190", text: "昼下がり", kind: "noun", tags: ["neutral", "light"], power: 2, slotMask: 7 },
  { id: "w191", text: "巡礼", kind: "noun", tags: ["travel", "light"], power: 4, slotMask: 7 },
  { id: "w192", text: "同盟", kind: "noun", tags: ["hero", "neutral"], power: 3, slotMask: 7 },
  { id: "w193", text: "陰謀", kind: "noun", tags: ["shadow", "mind"], power: 4, slotMask: 7 },
  { id: "w194", text: "講和", kind: "noun", tags: ["neutral", "mind"], power: 3, slotMask: 7 },
  { id: "w195", text: "祝杯", kind: "noun", tags: ["sound", "light"], power: 3, slotMask: 7 },
  { id: "w196", text: "邂逅", kind: "noun", tags: ["cosmos", "life"], power: 3, slotMask: 7 },
  { id: "w197", text: "旅立ち", kind: "noun", tags: ["travel", "wind"], power: 4, slotMask: 7 },
  { id: "w198", text: "帰還", kind: "noun", tags: ["travel", "earth"], power: 4, slotMask: 7 },
  { id: "w199", text: "怨嗟", kind: "noun", tags: ["shadow", "sound"], power: 4, slotMask: 7 },
  { id: "w200", text: "歓声", kind: "noun", tags: ["sound", "light"], power: 3, slotMask: 7 },
  { id: "w201", text: "沈黙", kind: "noun", tags: ["ice", "mind"], power: 3, slotMask: 7 },
  { id: "w202", text: "独白", kind: "noun", tags: ["mind", "neutral"], power: 3, slotMask: 7 },
  { id: "w203", text: "合唱", kind: "noun", tags: ["sound", "light"], power: 4, slotMask: 7 },
  { id: "w204", text: "囁き", kind: "noun", tags: ["shadow", "sound"], power: 2, slotMask: 7 },
  { id: "w205", text: "咆哮", kind: "noun", tags: ["fire", "sound"], power: 5, slotMask: 7 },
  { id: "w206", text: "鎖", kind: "noun", tags: ["metal", "shadow"], power: 3, slotMask: 7 },
  { id: "w207", text: "柵", kind: "noun", tags: ["earth", "neutral"], power: 2, slotMask: 7 },
  { id: "w208", text: "篝火", kind: "noun", tags: ["fire", "nature"], power: 3, slotMask: 7 },
  { id: "w209", text: "行商", kind: "noun", tags: ["trade", "travel"], power: 3, slotMask: 7 },
  { id: "w210", text: "密輸", kind: "noun", tags: ["shadow", "trade"], power: 3, slotMask: 7 },
  { id: "w211", text: "密談", kind: "noun", tags: ["shadow", "mind"], power: 3, slotMask: 7 },
  { id: "w212", text: "宣戦布告", kind: "noun", tags: ["hero", "fire"], power: 5, slotMask: 7 },
  { id: "w213", text: "休戦", kind: "noun", tags: ["neutral", "ice"], power: 2, slotMask: 7 },
  { id: "w214", text: "血統", kind: "noun", tags: ["life", "neutral"], power: 4, slotMask: 7 },
  { id: "w215", text: "系譜", kind: "noun", tags: ["mind", "earth"], power: 3, slotMask: 7 },
  { id: "w216", text: "遺言", kind: "noun", tags: ["shadow", "sound"], power: 4, slotMask: 7 },
  { id: "w217", text: "誓い", kind: "noun", tags: ["light", "hero"], power: 4, slotMask: 7 },
  { id: "w218", text: "背徳", kind: "noun", tags: ["shadow", "mind"], power: 3, slotMask: 7 },
  { id: "w219", text: "清廉", kind: "noun", tags: ["light", "mind"], power: 3, slotMask: 7 },
  { id: "w220", text: "焦燥", kind: "noun", tags: ["fire", "mind"], power: 3, slotMask: 7 },
  { id: "w221", text: "諦念", kind: "noun", tags: ["neutral", "mind"], power: 3, slotMask: 7 },
  { id: "w222", text: "野心", kind: "noun", tags: ["fire", "shadow"], power: 4, slotMask: 7 },
  { id: "w223", text: "恬淡", kind: "adj_na", tags: ["water", "mind"], power: 3, slotMask: 4 },
  { id: "w224", text: "荒々しい", kind: "adj_na", tags: ["wind", "fire"], power: 4, slotMask: 4 },
  { id: "w225", text: "しんとした", kind: "adj_na", tags: ["ice", "neutral"], power: 3, slotMask: 4 },
  { id: "w226", text: "うるわしい", kind: "adj_na", tags: ["light", "life"], power: 3, slotMask: 4 },
  { id: "w227", text: "みすぼらしい", kind: "adj_na", tags: ["shadow", "earth"], power: 2, slotMask: 4 },
  { id: "w228", text: "けだるい", kind: "adj_na", tags: ["neutral", "shadow"], power: 2, slotMask: 4 },
  { id: "w229", text: "ぎらついた", kind: "adj_na", tags: ["metal", "light"], power: 4, slotMask: 4 },
  { id: "w230", text: "ふわりとした", kind: "adj_na", tags: ["wind", "life"], power: 2, slotMask: 4 },
  { id: "w231", text: "けばけばしい", kind: "adj_na", tags: ["light", "sound"], power: 2, slotMask: 4 },
  { id: "w232", text: "物静か", kind: "adj_na", tags: ["ice", "mind"], power: 3, slotMask: 4 },
  { id: "w233", text: "気だるげ", kind: "adj_na", tags: ["neutral", "wind"], power: 2, slotMask: 4 },
  { id: "w234", text: "それゆえに", kind: "conj", tags: ["link", "fire"], power: 1, slotMask: 7 },
  { id: "w235", text: "すなわち", kind: "conj", tags: ["link", "mind"], power: 1, slotMask: 7 },
  { id: "w236", text: "もっとも", kind: "conj", tags: ["link", "neutral"], power: 1, slotMask: 7 },
  { id: "w237", text: "たとえ", kind: "conj", tags: ["link", "cosmos"], power: 1, slotMask: 7 },
  { id: "w238", text: "ならびに", kind: "conj", tags: ["link", "neutral"], power: 1, slotMask: 7 },
  { id: "w239", text: "および", kind: "conj", tags: ["link", "neutral"], power: 1, slotMask: 7 },
  { id: "w240", text: "かつ", kind: "conj", tags: ["link", "hero"], power: 1, slotMask: 7 },
  { id: "w241", text: "や", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w242", text: "牧場", kind: "noun", tags: ["nature","life"], power: 3, slotMask: 7 },
  { id: "w243", text: "高原", kind: "noun", tags: ["nature","wind"], power: 4, slotMask: 7 },
  { id: "w244", text: "渓谷", kind: "noun", tags: ["nature","water"], power: 4, slotMask: 7 },
  { id: "w245", text: "断崖", kind: "noun", tags: ["nature","earth"], power: 5, slotMask: 7 },
  { id: "w246", text: "湿地", kind: "noun", tags: ["nature","water"], power: 3, slotMask: 7 },
  { id: "w247", text: "湖畔", kind: "noun", tags: ["nature","water"], power: 3, slotMask: 7 },
  { id: "w248", text: "河原", kind: "noun", tags: ["nature","earth"], power: 2, slotMask: 7 },
  { id: "w249", text: "滝つぼ", kind: "noun", tags: ["nature","water"], power: 4, slotMask: 7 },
  { id: "w250", text: "鍾乳洞", kind: "noun", tags: ["nature","earth"], power: 4, slotMask: 7 },
  { id: "w251", text: "溶岩原", kind: "noun", tags: ["nature","fire"], power: 5, slotMask: 7 },
  { id: "w252", text: "砂丘", kind: "noun", tags: ["nature","wind"], power: 3, slotMask: 7 },
  { id: "w253", text: "樹海", kind: "noun", tags: ["nature","earth"], power: 4, slotMask: 7 },
  { id: "w254", text: "巨木", kind: "noun", tags: ["nature","life"], power: 4, slotMask: 7 },
  { id: "w255", text: "古木", kind: "noun", tags: ["nature","earth"], power: 3, slotMask: 7 },
  { id: "w256", text: "花弁", kind: "noun", tags: ["nature","life"], power: 2, slotMask: 7 },
  { id: "w257", text: "岩陰", kind: "noun", tags: ["nature","shadow"], power: 3, slotMask: 7 },
  { id: "w258", text: "地下湖", kind: "noun", tags: ["nature","water"], power: 4, slotMask: 7 },
  { id: "w259", text: "湧水", kind: "noun", tags: ["nature","water"], power: 3, slotMask: 7 },
  { id: "w260", text: "温泉", kind: "noun", tags: ["nature","fire"], power: 3, slotMask: 7 },
  { id: "w261", text: "間欠泉", kind: "noun", tags: ["nature","fire"], power: 4, slotMask: 7 },
  { id: "w262", text: "雪渓", kind: "noun", tags: ["nature","ice"], power: 4, slotMask: 7 },
  { id: "w263", text: "霧林", kind: "noun", tags: ["nature","water"], power: 3, slotMask: 7 },
  { id: "w264", text: "北極星", kind: "noun", tags: ["cosmos","ice"], power: 4, slotMask: 7 },
  { id: "w265", text: "天の川", kind: "noun", tags: ["cosmos","light"], power: 5, slotMask: 7 },
  { id: "w266", text: "隕石", kind: "noun", tags: ["cosmos","earth"], power: 5, slotMask: 7 },
  { id: "w267", text: "月面", kind: "noun", tags: ["cosmos","ice"], power: 4, slotMask: 7 },
  { id: "w268", text: "日食", kind: "noun", tags: ["cosmos","shadow"], power: 5, slotMask: 7 },
  { id: "w269", text: "霜柱", kind: "noun", tags: ["nature","ice"], power: 2, slotMask: 7 },
  { id: "w270", text: "雹", kind: "noun", tags: ["nature","ice"], power: 3, slotMask: 7 },
  { id: "w271", text: "津波", kind: "noun", tags: ["nature","water"], power: 6, slotMask: 7 },
  { id: "w272", text: "岩礁", kind: "noun", tags: ["nature","water"], power: 3, slotMask: 7 },
  { id: "w273", text: "深海", kind: "noun", tags: ["nature","water"], power: 5, slotMask: 7 },
  { id: "w274", text: "海溝", kind: "noun", tags: ["nature","water"], power: 6, slotMask: 7 },
  { id: "w275", text: "サンゴ礁", kind: "noun", tags: ["nature","life"], power: 3, slotMask: 7 },
  { id: "w276", text: "龍脈", kind: "noun", tags: ["fantasy","earth"], power: 5, slotMask: 7 },
  { id: "w277", text: "霊脈", kind: "noun", tags: ["shadow","life"], power: 4, slotMask: 7 },
  { id: "w278", text: "結界", kind: "noun", tags: ["shadow","light"], power: 5, slotMask: 7 },
  { id: "w279", text: "封印", kind: "noun", tags: ["shadow","mind"], power: 4, slotMask: 7 },
  { id: "w280", text: "加護", kind: "noun", tags: ["light","life"], power: 4, slotMask: 7 },
  { id: "w281", text: "神託", kind: "noun", tags: ["light","cosmos"], power: 5, slotMask: 7 },
  { id: "w282", text: "堕天使", kind: "noun", tags: ["shadow","fantasy"], power: 6, slotMask: 7 },
  { id: "w283", text: "熾天使", kind: "noun", tags: ["light","fantasy"], power: 7, slotMask: 7 },
  { id: "w284", text: "精霊王", kind: "noun", tags: ["fantasy","wind"], power: 7, slotMask: 7 },
  { id: "w285", text: "小人", kind: "noun", tags: ["fantasy","earth"], power: 3, slotMask: 7 },
  { id: "w286", text: "巨人", kind: "noun", tags: ["fantasy","earth"], power: 7, slotMask: 7 },
  { id: "w287", text: "石化", kind: "noun", tags: ["shadow","earth"], power: 4, slotMask: 7 },
  { id: "w288", text: "瘴気", kind: "noun", tags: ["shadow","nature"], power: 4, slotMask: 7 },
  { id: "w289", text: "聖域", kind: "noun", tags: ["light","earth"], power: 5, slotMask: 7 },
  { id: "w290", text: "魔境", kind: "noun", tags: ["shadow","nature"], power: 5, slotMask: 7 },
  { id: "w291", text: "秘境", kind: "noun", tags: ["nature","cosmos"], power: 4, slotMask: 7 },
  { id: "w292", text: "桃源郷", kind: "noun", tags: ["nature","life"], power: 4, slotMask: 7 },
  { id: "w293", text: "廃墟都市", kind: "noun", tags: ["shadow","earth"], power: 4, slotMask: 7 },
  { id: "w294", text: "市場", kind: "noun", tags: ["trade","neutral"], power: 3, slotMask: 7 },
  { id: "w295", text: "広場", kind: "noun", tags: ["neutral","earth"], power: 3, slotMask: 7 },
  { id: "w296", text: "噴水", kind: "noun", tags: ["water","light"], power: 3, slotMask: 7 },
  { id: "w297", text: "記念碑", kind: "noun", tags: ["earth","mind"], power: 3, slotMask: 7 },
  { id: "w298", text: "城壁", kind: "noun", tags: ["earth","metal"], power: 5, slotMask: 7 },
  { id: "w299", text: "堀", kind: "noun", tags: ["water","earth"], power: 3, slotMask: 7 },
  { id: "w300", text: "吊り橋", kind: "noun", tags: ["earth","wind"], power: 3, slotMask: 7 },
  { id: "w301", text: "鐘楼", kind: "noun", tags: ["sound","earth"], power: 4, slotMask: 7 },
  { id: "w302", text: "礼拝堂", kind: "noun", tags: ["light","neutral"], power: 3, slotMask: 7 },
  { id: "w303", text: "地下墓所", kind: "noun", tags: ["shadow","earth"], power: 4, slotMask: 7 },
  { id: "w304", text: "石棺", kind: "noun", tags: ["shadow","earth"], power: 4, slotMask: 7 },
  { id: "w305", text: "死霊術師", kind: "noun", tags: ["shadow","mage"], power: 5, slotMask: 7 },
  { id: "w306", text: "祝詞", kind: "noun", tags: ["light","sound"], power: 3, slotMask: 7 },
  { id: "w307", text: "呪文", kind: "noun", tags: ["shadow","sound"], power: 4, slotMask: 7 },
  { id: "w308", text: "魔法陣", kind: "noun", tags: ["fantasy","cosmos"], power: 4, slotMask: 7 },
  { id: "w309", text: "魔導書", kind: "noun", tags: ["mage","mind"], power: 5, slotMask: 7 },
  { id: "w310", text: "禁書", kind: "noun", tags: ["shadow","mind"], power: 5, slotMask: 7 },
  { id: "w311", text: "聖剣", kind: "noun", tags: ["metal","light"], power: 7, slotMask: 7 },
  { id: "w312", text: "魔剣", kind: "noun", tags: ["metal","shadow"], power: 7, slotMask: 7 },
  { id: "w313", text: "妖刀", kind: "noun", tags: ["metal","shadow"], power: 6, slotMask: 7 },
  { id: "w314", text: "暗器", kind: "noun", tags: ["shadow","metal"], power: 3, slotMask: 7 },
  { id: "w315", text: "戦斧", kind: "noun", tags: ["metal","hero"], power: 5, slotMask: 7 },
  { id: "w316", text: "弩", kind: "noun", tags: ["metal","wind"], power: 4, slotMask: 7 },
  { id: "w317", text: "鎧", kind: "noun", tags: ["metal","earth"], power: 5, slotMask: 7 },
  { id: "w318", text: "仮面", kind: "noun", tags: ["shadow","mind"], power: 3, slotMask: 7 },
  { id: "w319", text: "舞踏会", kind: "noun", tags: ["sound","light"], power: 4, slotMask: 7 },
  { id: "w320", text: "家臣", kind: "noun", tags: ["hero","earth"], power: 4, slotMask: 7 },
  { id: "w321", text: "紋章", kind: "noun", tags: ["light","earth"], power: 3, slotMask: 7 },
  { id: "w322", text: "軍旗", kind: "noun", tags: ["hero","wind"], power: 4, slotMask: 7 },
  { id: "w323", text: "奇襲", kind: "noun", tags: ["shadow","wind"], power: 5, slotMask: 7 },
  { id: "w324", text: "包囲", kind: "noun", tags: ["earth","hero"], power: 4, slotMask: 7 },
  { id: "w325", text: "兵糧", kind: "noun", tags: ["life","earth"], power: 3, slotMask: 7 },
  { id: "w326", text: "水筒", kind: "noun", tags: ["water","travel"], power: 2, slotMask: 7 },
  { id: "w327", text: "星読み", kind: "noun", tags: ["cosmos","mind"], power: 4, slotMask: 7 },
  { id: "w328", text: "占星", kind: "noun", tags: ["cosmos","mind"], power: 4, slotMask: 7 },
  { id: "w329", text: "太鼓", kind: "noun", tags: ["sound","earth"], power: 3, slotMask: 7 },
  { id: "w330", text: "琵琶", kind: "noun", tags: ["sound","mind"], power: 3, slotMask: 7 },
  { id: "w331", text: "狂言", kind: "noun", tags: ["sound","light"], power: 3, slotMask: 7 },
  { id: "w332", text: "奇術", kind: "noun", tags: ["shadow","mind"], power: 3, slotMask: 7 },
  { id: "w333", text: "錬金", kind: "noun", tags: ["mage","fire"], power: 4, slotMask: 7 },
  { id: "w334", text: "結晶", kind: "noun", tags: ["ice","earth"], power: 3, slotMask: 7 },
  { id: "w335", text: "鉱脈", kind: "noun", tags: ["earth","metal"], power: 4, slotMask: 7 },
  { id: "w336", text: "鍛冶", kind: "noun", tags: ["fire","craft"], power: 5, slotMask: 7 },
  { id: "w337", text: "鋼", kind: "noun", tags: ["metal","earth"], power: 4, slotMask: 7 },
  { id: "w338", text: "松明", kind: "noun", tags: ["fire","light"], power: 2, slotMask: 7 },
  { id: "w339", text: "行灯", kind: "noun", tags: ["light","neutral"], power: 2, slotMask: 7 },
  { id: "w340", text: "風鈴", kind: "noun", tags: ["sound","wind"], power: 2, slotMask: 7 },
  { id: "w341", text: "染料", kind: "noun", tags: ["craft","water"], power: 2, slotMask: 7 },
  { id: "w342", text: "漆器", kind: "noun", tags: ["craft","earth"], power: 3, slotMask: 7 },
  { id: "w343", text: "陶器", kind: "noun", tags: ["earth","craft"], power: 3, slotMask: 7 },
  { id: "w344", text: "機織り", kind: "noun", tags: ["craft","earth"], power: 3, slotMask: 7 },
  { id: "w345", text: "庖丁", kind: "noun", tags: ["metal","life"], power: 3, slotMask: 7 },
  { id: "w346", text: "燻製", kind: "noun", tags: ["fire","life"], power: 3, slotMask: 7 },
  { id: "w347", text: "味噌", kind: "noun", tags: ["life","earth"], power: 2, slotMask: 7 },
  { id: "w348", text: "毒薬", kind: "noun", tags: ["shadow","life"], power: 4, slotMask: 7 },
  { id: "w349", text: "解毒剤", kind: "noun", tags: ["light","life"], power: 3, slotMask: 7 },
  { id: "w350", text: "鍼", kind: "noun", tags: ["life","metal"], power: 2, slotMask: 7 },
  { id: "w351", text: "瞑想", kind: "noun", tags: ["mind","ice"], power: 3, slotMask: 7 },
  { id: "w352", text: "修行", kind: "noun", tags: ["hero","earth"], power: 4, slotMask: 7 },
  { id: "w353", text: "福音", kind: "noun", tags: ["light","sound"], power: 4, slotMask: 7 },
  { id: "w354", text: "経典", kind: "noun", tags: ["light","mind"], power: 4, slotMask: 7 },
  { id: "w355", text: "異端", kind: "noun", tags: ["shadow","fire"], power: 4, slotMask: 7 },
  { id: "w356", text: "火刑", kind: "noun", tags: ["fire","shadow"], power: 5, slotMask: 7 },
  { id: "w357", text: "墓守", kind: "noun", tags: ["shadow","earth"], power: 3, slotMask: 7 },
  { id: "w358", text: "棺", kind: "noun", tags: ["shadow","earth"], power: 3, slotMask: 7 },
  { id: "w359", text: "仏壇", kind: "noun", tags: ["light","earth"], power: 3, slotMask: 7 },
  { id: "w360", text: "神酒", kind: "noun", tags: ["light","water"], power: 3, slotMask: 7 },
  { id: "w361", text: "茶碗", kind: "noun", tags: ["earth","life"], power: 2, slotMask: 7 },
  { id: "w362", text: "白刃", kind: "noun", tags: ["metal","light"], power: 4, slotMask: 7 },
  { id: "w363", text: "血痕", kind: "noun", tags: ["shadow","water"], power: 3, slotMask: 7 },
  { id: "w364", text: "刺青", kind: "noun", tags: ["shadow","craft"], power: 3, slotMask: 7 },
  { id: "w365", text: "櫛", kind: "noun", tags: ["craft","neutral"], power: 2, slotMask: 7 },
  { id: "w366", text: "金貨", kind: "noun", tags: ["metal","trade"], power: 3, slotMask: 7 },
  { id: "w367", text: "賭場", kind: "noun", tags: ["shadow","fire"], power: 4, slotMask: 7 },
  { id: "w368", text: "千術", kind: "noun", tags: ["shadow","mind"], power: 4, slotMask: 7 },
  { id: "w369", text: "車輪", kind: "noun", tags: ["metal","earth"], power: 3, slotMask: 7 },
  { id: "w370", text: "軍馬", kind: "noun", tags: ["hero","life"], power: 5, slotMask: 7 },
  { id: "w371", text: "象", kind: "noun", tags: ["life","earth"], power: 6, slotMask: 7 },
  { id: "w372", text: "獅子", kind: "noun", tags: ["life","hero"], power: 6, slotMask: 7 },
  { id: "w373", text: "虎", kind: "noun", tags: ["life","shadow"], power: 6, slotMask: 7 },
  { id: "w374", text: "熊", kind: "noun", tags: ["life","earth"], power: 5, slotMask: 7 },
  { id: "w375", text: "漁火", kind: "noun", tags: ["water","light"], power: 3, slotMask: 7 },
  { id: "w376", text: "網", kind: "noun", tags: ["water","craft"], power: 3, slotMask: 7 },
  { id: "w377", text: "潮騒", kind: "noun", tags: ["water","sound"], power: 3, slotMask: 7 },
  { id: "w378", text: "焚き火", kind: "noun", tags: ["fire","nature"], power: 3, slotMask: 7 },
  { id: "w379", text: "薫香", kind: "noun", tags: ["light","fire"], power: 2, slotMask: 7 },
  { id: "w380", text: "白檀", kind: "noun", tags: ["light","earth"], power: 3, slotMask: 7 },
  { id: "w381", text: "防虫", kind: "noun", tags: ["life","earth"], power: 2, slotMask: 7 },
  { id: "w382", text: "菖蒲", kind: "noun", tags: ["life","water"], power: 2, slotMask: 7 },
  { id: "w383", text: "斧", kind: "noun", tags: ["metal","earth"], power: 3, slotMask: 7 },
  { id: "w384", text: "錆", kind: "noun", tags: ["metal","shadow"], power: 2, slotMask: 7 },
  { id: "w385", text: "怒号", kind: "noun", tags: ["fire","sound"], power: 4, slotMask: 7 },
  { id: "w386", text: "嘲笑", kind: "noun", tags: ["shadow","sound"], power: 3, slotMask: 7 },
  { id: "w387", text: "謝罪", kind: "noun", tags: ["shadow","mind"], power: 3, slotMask: 7 },
  { id: "w388", text: "復讐", kind: "noun", tags: ["shadow","fire"], power: 5, slotMask: 7 },
  { id: "w389", text: "天命", kind: "noun", tags: ["cosmos","light"], power: 5, slotMask: 7 },
  { id: "w390", text: "凶兆", kind: "noun", tags: ["cosmos","shadow"], power: 3, slotMask: 7 },
  { id: "w391", text: "蜃気楼", kind: "noun", tags: ["water","light"], power: 3, slotMask: 7 },
  { id: "w392", text: "鬼火", kind: "noun", tags: ["fire","shadow"], power: 3, slotMask: 7 },
  { id: "w393", text: "雪崩", kind: "noun", tags: ["ice","earth"], power: 6, slotMask: 7 },
  { id: "w394", text: "地割れ", kind: "noun", tags: ["earth","nature"], power: 5, slotMask: 7 },
  { id: "w395", text: "清流", kind: "noun", tags: ["water","light"], power: 3, slotMask: 7 },
  { id: "w396", text: "濁流", kind: "noun", tags: ["water","shadow"], power: 4, slotMask: 7 },
  { id: "w397", text: "水車", kind: "noun", tags: ["water","craft"], power: 4, slotMask: 7 },
  { id: "w398", text: "釜", kind: "noun", tags: ["metal","fire"], power: 3, slotMask: 7 },
  { id: "w399", text: "囲炉裏", kind: "noun", tags: ["fire","earth"], power: 3, slotMask: 7 },
  { id: "w400", text: "烙印", kind: "noun", tags: ["fire","shadow"], power: 3, slotMask: 7 },
  { id: "w401", text: "解放", kind: "noun", tags: ["light","wind"], power: 4, slotMask: 7 },
  { id: "w402", text: "貴族", kind: "noun", tags: ["light","neutral"], power: 4, slotMask: 7 },
  { id: "w403", text: "農民", kind: "noun", tags: ["earth","life"], power: 3, slotMask: 7 },
  { id: "w404", text: "芸術", kind: "noun", tags: ["light","mind"], power: 4, slotMask: 7 },
  { id: "w405", text: "旋律", kind: "noun", tags: ["sound","wind"], power: 3, slotMask: 7 },
  { id: "w406", text: "無音", kind: "noun", tags: ["ice","neutral"], power: 2, slotMask: 7 },
  { id: "w407", text: "奥義", kind: "noun", tags: ["shadow","mind"], power: 5, slotMask: 7 },
  { id: "w408", text: "真髄", kind: "noun", tags: ["mind","light"], power: 5, slotMask: 7 },
  { id: "w409", text: "汚名", kind: "noun", tags: ["shadow","neutral"], power: 3, slotMask: 7 },
  { id: "w410", text: "潔白", kind: "noun", tags: ["light","ice"], power: 4, slotMask: 7 },
  { id: "w411", text: "判決", kind: "noun", tags: ["mind","neutral"], power: 4, slotMask: 7 },
  { id: "w412", text: "手錠", kind: "noun", tags: ["shadow","metal"], power: 3, slotMask: 7 },
  { id: "w413", text: "逃亡", kind: "noun", tags: ["shadow","wind"], power: 3, slotMask: 7 },
  { id: "w414", text: "斥候", kind: "noun", tags: ["hero","wind"], power: 3, slotMask: 7 },
  { id: "w415", text: "暗号", kind: "noun", tags: ["shadow","mind"], power: 3, slotMask: 7 },
  { id: "w416", text: "関所", kind: "noun", tags: ["earth","neutral"], power: 3, slotMask: 7 },
  { id: "w417", text: "虎口", kind: "noun", tags: ["shadow","metal"], power: 4, slotMask: 7 },
  { id: "w418", text: "化け狸", kind: "noun", tags: ["shadow","life"], power: 4, slotMask: 7 },
  { id: "w419", text: "妖狐", kind: "noun", tags: ["shadow","life"], power: 5, slotMask: 7 },
  { id: "w420", text: "九尾", kind: "noun", tags: ["fantasy","fire"], power: 7, slotMask: 7 },
  { id: "w421", text: "牙", kind: "noun", tags: ["life","metal"], power: 3, slotMask: 7 },
  { id: "w422", text: "翼", kind: "noun", tags: ["wind","life"], power: 4, slotMask: 7 },
  { id: "w423", text: "漂泊", kind: "noun", tags: ["water","travel"], power: 3, slotMask: 7 },
  { id: "w424", text: "帰路", kind: "noun", tags: ["travel","earth"], power: 3, slotMask: 7 },
  { id: "w425", text: "終末", kind: "noun", tags: ["shadow","cosmos"], power: 5, slotMask: 7 },
  { id: "w426", text: "輪廻", kind: "noun", tags: ["cosmos","life"], power: 5, slotMask: 7 },
  { id: "w427", text: "涅槃", kind: "noun", tags: ["light","ice"], power: 6, slotMask: 7 },
  { id: "w428", text: "迷宮入り", kind: "noun", tags: ["shadow","mind"], power: 4, slotMask: 7 },
  { id: "w429", text: "悪夢", kind: "noun", tags: ["shadow","cosmos"], power: 4, slotMask: 7 },
  { id: "w430", text: "妖怪", kind: "noun", tags: ["shadow","life"], power: 4, slotMask: 7 },
  { id: "w431", text: "魔王", kind: "noun", tags: ["shadow","fantasy"], power: 8, slotMask: 7 },
  { id: "w432", text: "魔王城", kind: "noun", tags: ["shadow","earth"], power: 7, slotMask: 7 },
  { id: "w433", text: "絆", kind: "noun", tags: ["light","life"], power: 4, slotMask: 7 },
  { id: "w434", text: "縁結び", kind: "noun", tags: ["cosmos","life"], power: 3, slotMask: 7 },
  { id: "w435", text: "望楼", kind: "noun", tags: ["earth","wind"], power: 3, slotMask: 7 },
  { id: "w436", text: "矢倉", kind: "noun", tags: ["earth","metal"], power: 3, slotMask: 7 },
  { id: "w437", text: "天守", kind: "noun", tags: ["earth","hero"], power: 5, slotMask: 7 },
  { id: "w438", text: "外堀", kind: "noun", tags: ["water","earth"], power: 3, slotMask: 7 },
  { id: "w439", text: "内堀", kind: "noun", tags: ["water","earth"], power: 3, slotMask: 7 },
  { id: "w440", text: "空堀", kind: "noun", tags: ["earth","shadow"], power: 3, slotMask: 7 },
  { id: "w441", text: "柵門", kind: "noun", tags: ["earth","metal"], power: 3, slotMask: 7 },
  { id: "w442", text: "矢来", kind: "noun", tags: ["earth","wind"], power: 2, slotMask: 7 },
  { id: "w443", text: "土塁", kind: "noun", tags: ["earth","hero"], power: 3, slotMask: 7 },
  { id: "w444", text: "胸壁", kind: "noun", tags: ["earth","metal"], power: 3, slotMask: 7 },
  { id: "w445", text: "砦", kind: "noun", tags: ["earth","hero"], power: 4, slotMask: 7 },
  { id: "w446", text: "陣屋", kind: "noun", tags: ["earth","neutral"], power: 3, slotMask: 7 },
  { id: "w447", text: "陣鐘", kind: "noun", tags: ["sound","earth"], power: 3, slotMask: 7 },
  { id: "w448", text: "陣太鼓", kind: "noun", tags: ["sound","earth"], power: 4, slotMask: 7 },
  { id: "w449", text: "合戦", kind: "noun", tags: ["hero","fire"], power: 5, slotMask: 7 },
  { id: "w450", text: "白兵", kind: "noun", tags: ["hero","metal"], power: 4, slotMask: 7 },
  { id: "w451", text: "白刃取り", kind: "noun", tags: ["hero","metal"], power: 5, slotMask: 7 },
  { id: "w452", text: "流鏑馬", kind: "noun", tags: ["hero","wind"], power: 5, slotMask: 7 },
  { id: "w453", text: "騎射", kind: "noun", tags: ["hero","wind"], power: 4, slotMask: 7 },
  { id: "w454", text: "歩兵", kind: "noun", tags: ["hero","earth"], power: 4, slotMask: 7 },
  { id: "w455", text: "槍兵", kind: "noun", tags: ["hero","metal"], power: 4, slotMask: 7 },
  { id: "w456", text: "弓兵", kind: "noun", tags: ["hero","wind"], power: 4, slotMask: 7 },
  { id: "w457", text: "鉄砲隊", kind: "noun", tags: ["hero","metal"], power: 5, slotMask: 7 },
  { id: "w458", text: "大筒", kind: "noun", tags: ["metal","fire"], power: 6, slotMask: 7 },
  { id: "w459", text: "石火矢", kind: "noun", tags: ["fire","metal"], power: 5, slotMask: 7 },
  { id: "w460", text: "火箭", kind: "noun", tags: ["fire","wind"], power: 5, slotMask: 7 },
  { id: "w461", text: "火矢", kind: "noun", tags: ["fire","wind"], power: 4, slotMask: 7 },
  { id: "w462", text: "狼煙", kind: "noun", tags: ["fire","wind"], power: 4, slotMask: 7 },
  { id: "w463", text: "烽火", kind: "noun", tags: ["fire","light"], power: 4, slotMask: 7 },
  { id: "w464", text: "狼煙台", kind: "noun", tags: ["fire","earth"], power: 3, slotMask: 7 },
  { id: "w465", text: "斥候鷹", kind: "noun", tags: ["wind","hero"], power: 4, slotMask: 7 },
  { id: "w466", text: "伝書鳩", kind: "noun", tags: ["wind","travel"], power: 2, slotMask: 7 },
  { id: "w467", text: "伝馬", kind: "noun", tags: ["life","travel"], power: 3, slotMask: 7 },
  { id: "w468", text: "駕籠", kind: "noun", tags: ["travel","earth"], power: 3, slotMask: 7 },
  { id: "w469", text: "駕籠舁き", kind: "noun", tags: ["travel","earth"], power: 2, slotMask: 7 },
  { id: "w470", text: "街道", kind: "noun", tags: ["travel","earth"], power: 3, slotMask: 7 },
  { id: "w471", text: "山道", kind: "noun", tags: ["travel","earth"], power: 3, slotMask: 7 },
  { id: "w472", text: "峠", kind: "noun", tags: ["travel","wind"], power: 4, slotMask: 7 },
  { id: "w473", text: "峠道", kind: "noun", tags: ["travel","wind"], power: 3, slotMask: 7 },
  { id: "w474", text: "隘路", kind: "noun", tags: ["earth","shadow"], power: 3, slotMask: 7 },
  { id: "w475", text: "狭谷", kind: "noun", tags: ["nature","earth"], power: 4, slotMask: 7 },
  { id: "w476", text: "峡谷", kind: "noun", tags: ["nature","earth"], power: 4, slotMask: 7 },
  { id: "w477", text: "山峡", kind: "noun", tags: ["nature","wind"], power: 3, slotMask: 7 },
  { id: "w478", text: "山頂", kind: "noun", tags: ["nature","wind"], power: 4, slotMask: 7 },
  { id: "w479", text: "山麓", kind: "noun", tags: ["nature","earth"], power: 3, slotMask: 7 },
  { id: "w480", text: "山小屋", kind: "noun", tags: ["nature","earth"], power: 3, slotMask: 7 },
  { id: "w481", text: "避難小屋", kind: "noun", tags: ["nature","earth"], power: 2, slotMask: 7 },
  { id: "w482", text: "雪洞", kind: "noun", tags: ["ice","earth"], power: 2, slotMask: 7 },
  { id: "w483", text: "氷室", kind: "noun", tags: ["ice","earth"], power: 3, slotMask: 7 },
  { id: "w484", text: "氷漬け", kind: "noun", tags: ["ice","water"], power: 3, slotMask: 7 },
  { id: "w485", text: "冷蔵", kind: "noun", tags: ["ice","neutral"], power: 2, slotMask: 7 },
  { id: "w486", text: "冷気", kind: "noun", tags: ["ice","wind"], power: 3, slotMask: 7 },
  { id: "w487", text: "熱気", kind: "noun", tags: ["fire","wind"], power: 3, slotMask: 7 },
  { id: "w488", text: "陽炎", kind: "noun", tags: ["fire","wind"], power: 3, slotMask: 7 },
  { id: "w489", text: "地熱", kind: "noun", tags: ["fire","earth"], power: 4, slotMask: 7 },
  { id: "w490", text: "温泉街", kind: "noun", tags: ["fire","trade"], power: 3, slotMask: 7 },
  { id: "w491", text: "湯治", kind: "noun", tags: ["water","life"], power: 3, slotMask: 7 },
  { id: "w492", text: "湯煙", kind: "noun", tags: ["water","fire"], power: 2, slotMask: 7 },
  { id: "w493", text: "湯気", kind: "noun", tags: ["water","fire"], power: 2, slotMask: 7 },
  { id: "w494", text: "湯船", kind: "noun", tags: ["water","life"], power: 2, slotMask: 7 },
  { id: "w495", text: "湯舟", kind: "noun", tags: ["water","life"], power: 2, slotMask: 7 },
  { id: "w496", text: "桶", kind: "noun", tags: ["water","earth"], power: 2, slotMask: 7 },
  { id: "w497", text: "手桶", kind: "noun", tags: ["water","life"], power: 1, slotMask: 7 },
  { id: "w498", text: "柄杓", kind: "noun", tags: ["water","craft"], power: 1, slotMask: 7 },
  { id: "w499", text: "柄杓屋", kind: "noun", tags: ["trade","neutral"], power: 2, slotMask: 7 },
  { id: "w500", text: "水屋", kind: "noun", tags: ["water","trade"], power: 2, slotMask: 7 },
  /* 句読点・記号（助詞扱い・初期入手・ガチャ対象外） */
  { id: "w501", text: "、", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w502", text: "。", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w503", text: "・", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w504", text: "「", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w505", text: "」", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w506", text: "…", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w507", text: "？", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w508", text: "！", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w509", text: "：", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w510", text: "；", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w511", text: "（", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  { id: "w512", text: "）", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  /* 助詞「に」（初期入手・ガチャ対象外は app.js の STARTER_GRAMMAR_IDS で指定） */
  { id: "w513", text: "に", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },
  /* 漢数字（一〜九・十・百・千） */
  { id: "w514", text: "一", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w515", text: "二", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w516", text: "三", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w517", text: "四", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w518", text: "五", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w519", text: "六", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w520", text: "七", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w521", text: "八", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w522", text: "九", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w523", text: "十", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w524", text: "百", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w525", text: "千", kind: "noun", tags: ["neutral", "mind"], power: 1, slotMask: 7 },
  { id: "w526", text: "狂気", kind: "noun", tags: ["shadow", "mind"], power: 5, slotMask: 7 },
  { id: "w527", text: "山脈", kind: "noun", tags: ["nature", "earth"], power: 6, slotMask: 7 },
  { id: "w528", text: "狂", kind: "noun", tags: ["shadow", "mind"], power: 4, slotMask: 7 },
  { id: "w529", text: "脈", kind: "noun", tags: ["earth", "life"], power: 4, slotMask: 7 },
];
