/** One-off generator: outputs lines for words.js w242–w500 */
const fs = require("fs");
const path = require("path");

const nouns = [
  ["牧場", "nature", "life", 3],
  ["高原", "nature", "wind", 4],
  ["渓谷", "nature", "water", 4],
  ["断崖", "nature", "earth", 5],
  ["湿地", "nature", "water", 3],
  ["湖畔", "nature", "water", 3],
  ["河原", "nature", "earth", 2],
  ["滝つぼ", "nature", "water", 4],
  ["鍾乳洞", "nature", "earth", 4],
  ["溶岩原", "nature", "fire", 5],
  ["砂丘", "nature", "wind", 3],
  ["樹海", "nature", "earth", 4],
  ["巨木", "nature", "life", 4],
  ["古木", "nature", "earth", 3],
  ["花弁", "nature", "life", 2],
  ["岩陰", "nature", "shadow", 3],
  ["地下湖", "nature", "water", 4],
  ["湧水", "nature", "water", 3],
  ["温泉", "nature", "fire", 3],
  ["間欠泉", "nature", "fire", 4],
  ["雪渓", "nature", "ice", 4],
  ["霧林", "nature", "water", 3],
  ["北極星", "cosmos", "ice", 4],
  ["天の川", "cosmos", "light", 5],
  ["隕石", "cosmos", "earth", 5],
  ["月面", "cosmos", "ice", 4],
  ["日食", "cosmos", "shadow", 5],
  ["霜柱", "nature", "ice", 2],
  ["雹", "nature", "ice", 3],
  ["津波", "nature", "water", 6],
  ["岩礁", "nature", "water", 3],
  ["深海", "nature", "water", 5],
  ["海溝", "nature", "water", 6],
  ["サンゴ礁", "nature", "life", 3],
  ["龍脈", "fantasy", "earth", 5],
  ["霊脈", "shadow", "life", 4],
  ["結界", "shadow", "light", 5],
  ["封印", "shadow", "mind", 4],
  ["加護", "light", "life", 4],
  ["神託", "light", "cosmos", 5],
  ["堕天使", "shadow", "fantasy", 6],
  ["熾天使", "light", "fantasy", 7],
  ["精霊王", "fantasy", "wind", 7],
  ["小人", "fantasy", "earth", 3],
  ["巨人", "fantasy", "earth", 7],
  ["石化", "shadow", "earth", 4],
  ["瘴気", "shadow", "nature", 4],
  ["聖域", "light", "earth", 5],
  ["魔境", "shadow", "nature", 5],
  ["秘境", "nature", "cosmos", 4],
  ["桃源郷", "nature", "life", 4],
  ["廃墟都市", "shadow", "earth", 4],
  ["市場", "trade", "neutral", 3],
  ["広場", "neutral", "earth", 3],
  ["噴水", "water", "light", 3],
  ["記念碑", "earth", "mind", 3],
  ["城壁", "earth", "metal", 5],
  ["堀", "water", "earth", 3],
  ["吊り橋", "earth", "wind", 3],
  ["鐘楼", "sound", "earth", 4],
  ["礼拝堂", "light", "neutral", 3],
  ["地下墓所", "shadow", "earth", 4],
  ["石棺", "shadow", "earth", 4],
  ["死霊術師", "shadow", "mage", 5],
  ["祝詞", "light", "sound", 3],
  ["呪文", "shadow", "sound", 4],
  ["魔法陣", "fantasy", "cosmos", 4],
  ["魔導書", "mage", "mind", 5],
  ["禁書", "shadow", "mind", 5],
  ["聖剣", "metal", "light", 7],
  ["魔剣", "metal", "shadow", 7],
  ["妖刀", "metal", "shadow", 6],
  ["暗器", "shadow", "metal", 3],
  ["戦斧", "metal", "hero", 5],
  ["弩", "metal", "wind", 4],
  ["鎧", "metal", "earth", 5],
  ["仮面", "shadow", "mind", 3],
  ["舞踏会", "sound", "light", 4],
  ["家臣", "hero", "earth", 4],
  ["紋章", "light", "earth", 3],
  ["軍旗", "hero", "wind", 4],
  ["奇襲", "shadow", "wind", 5],
  ["包囲", "earth", "hero", 4],
  ["兵糧", "life", "earth", 3],
  ["水筒", "water", "travel", 2],
  ["星読み", "cosmos", "mind", 4],
  ["占星", "cosmos", "mind", 4],
  ["太鼓", "sound", "earth", 3],
  ["琵琶", "sound", "mind", 3],
  ["狂言", "sound", "light", 3],
  ["奇術", "shadow", "mind", 3],
  ["錬金", "mage", "fire", 4],
  ["結晶", "ice", "earth", 3],
  ["鉱脈", "earth", "metal", 4],
  ["鍛冶", "fire", "craft", 5],
  ["鋼", "metal", "earth", 4],
  ["松明", "fire", "light", 2],
  ["行灯", "light", "neutral", 2],
  ["風鈴", "sound", "wind", 2],
  ["染料", "craft", "water", 2],
  ["漆器", "craft", "earth", 3],
  ["陶器", "earth", "craft", 3],
  ["機織り", "craft", "earth", 3],
  ["庖丁", "metal", "life", 3],
  ["燻製", "fire", "life", 3],
  ["味噌", "life", "earth", 2],
  ["毒薬", "shadow", "life", 4],
  ["解毒剤", "light", "life", 3],
  ["鍼", "life", "metal", 2],
  ["瞑想", "mind", "ice", 3],
  ["修行", "hero", "earth", 4],
  ["福音", "light", "sound", 4],
  ["経典", "light", "mind", 4],
  ["異端", "shadow", "fire", 4],
  ["火刑", "fire", "shadow", 5],
  ["墓守", "shadow", "earth", 3],
  ["棺", "shadow", "earth", 3],
  ["仏壇", "light", "earth", 3],
  ["神酒", "light", "water", 3],
  ["茶碗", "earth", "life", 2],
  ["白刃", "metal", "light", 4],
  ["血痕", "shadow", "water", 3],
  ["刺青", "shadow", "craft", 3],
  ["櫛", "craft", "neutral", 2],
  ["金貨", "metal", "trade", 3],
  ["賭場", "shadow", "fire", 4],
  ["千術", "shadow", "mind", 4],
  ["車輪", "metal", "earth", 3],
  ["軍馬", "hero", "life", 5],
  ["象", "life", "earth", 6],
  ["獅子", "life", "hero", 6],
  ["虎", "life", "shadow", 6],
  ["熊", "life", "earth", 5],
  ["漁火", "water", "light", 3],
  ["網", "water", "craft", 3],
  ["潮騒", "water", "sound", 3],
  ["焚き火", "fire", "nature", 3],
  ["薫香", "light", "fire", 2],
  ["白檀", "light", "earth", 3],
  ["防虫", "life", "earth", 2],
  ["菖蒲", "life", "water", 2],
  ["斧", "metal", "earth", 3],
  ["錆", "metal", "shadow", 2],
  ["怒号", "fire", "sound", 4],
  ["歓声", "sound", "light", 3],
  ["嘲笑", "shadow", "sound", 3],
  ["謝罪", "shadow", "mind", 3],
  ["復讐", "shadow", "fire", 5],
  ["天命", "cosmos", "light", 5],
  ["凶兆", "cosmos", "shadow", 3],
  ["蜃気楼", "water", "light", 3],
  ["鬼火", "fire", "shadow", 3],
  ["雪崩", "ice", "earth", 6],
  ["地割れ", "earth", "nature", 5],
  ["清流", "water", "light", 3],
  ["濁流", "water", "shadow", 4],
  ["水車", "water", "craft", 4],
  ["釜", "metal", "fire", 3],
  ["囲炉裏", "fire", "earth", 3],
  ["烙印", "fire", "shadow", 3],
  ["解放", "light", "wind", 4],
  ["貴族", "light", "neutral", 4],
  ["農民", "earth", "life", 3],
  ["芸術", "light", "mind", 4],
  ["旋律", "sound", "wind", 3],
  ["無音", "ice", "neutral", 2],
  ["奥義", "shadow", "mind", 5],
  ["真髄", "mind", "light", 5],
  ["汚名", "shadow", "neutral", 3],
  ["潔白", "light", "ice", 4],
  ["判決", "mind", "neutral", 4],
  ["手錠", "shadow", "metal", 3],
  ["逃亡", "shadow", "wind", 3],
  ["斥候", "hero", "wind", 3],
  ["暗号", "shadow", "mind", 3],
  ["関所", "earth", "neutral", 3],
  ["虎口", "shadow", "metal", 4],
  ["化け狸", "shadow", "life", 4],
  ["妖狐", "shadow", "life", 5],
  ["九尾", "fantasy", "fire", 7],
  ["牙", "life", "metal", 3],
  ["翼", "wind", "life", 4],
  ["漂泊", "water", "travel", 3],
  ["帰路", "travel", "earth", 3],
  ["終末", "shadow", "cosmos", 5],
  ["輪廻", "cosmos", "life", 5],
  ["涅槃", "light", "ice", 6],
  ["迷宮入り", "shadow", "mind", 4],
  ["悪夢", "shadow", "cosmos", 4],
  ["妖怪", "shadow", "life", 4],
  ["魔王", "shadow", "fantasy", 8],
  ["魔王城", "shadow", "earth", 7],
  ["絆", "light", "life", 4],
  ["縁結び", "cosmos", "life", 3],
  ["望楼", "earth", "wind", 3],
  ["矢倉", "earth", "metal", 3],
  ["天守", "earth", "hero", 5],
  ["外堀", "water", "earth", 3],
  ["内堀", "water", "earth", 3],
  ["空堀", "earth", "shadow", 3],
  ["柵門", "earth", "metal", 3],
  ["矢来", "earth", "wind", 2],
  ["土塁", "earth", "hero", 3],
  ["胸壁", "earth", "metal", 3],
  ["砦", "earth", "hero", 4],
  ["陣屋", "earth", "neutral", 3],
  ["陣鐘", "sound", "earth", 3],
  ["陣太鼓", "sound", "earth", 4],
  ["合戦", "hero", "fire", 5],
  ["白兵", "hero", "metal", 4],
  ["白刃取り", "hero", "metal", 5],
  ["流鏑馬", "hero", "wind", 5],
  ["騎射", "hero", "wind", 4],
  ["歩兵", "hero", "earth", 4],
  ["槍兵", "hero", "metal", 4],
  ["弓兵", "hero", "wind", 4],
  ["鉄砲隊", "hero", "metal", 5],
  ["大筒", "metal", "fire", 6],
  ["石火矢", "fire", "metal", 5],
  ["火箭", "fire", "wind", 5],
  ["火矢", "fire", "wind", 4],
  ["狼煙", "fire", "wind", 4],
  ["烽火", "fire", "light", 4],
  ["狼煙台", "fire", "earth", 3],
  ["斥候鷹", "wind", "hero", 4],
  ["伝書鳩", "wind", "travel", 2],
  ["伝馬", "life", "travel", 3],
  ["駕籠", "travel", "earth", 3],
  ["駕籠舁き", "travel", "earth", 2],
  ["街道", "travel", "earth", 3],
  ["山道", "travel", "earth", 3],
  ["峠", "travel", "wind", 4],
  ["峠道", "travel", "wind", 3],
  ["隘路", "earth", "shadow", 3],
  ["狭谷", "nature", "earth", 4],
  ["峡谷", "nature", "earth", 4],
  ["山峡", "nature", "wind", 3],
  ["山頂", "nature", "wind", 4],
  ["山麓", "nature", "earth", 3],
  ["山小屋", "nature", "earth", 3],
  ["避難小屋", "nature", "earth", 2],
  ["雪洞", "ice", "earth", 2],
  ["氷室", "ice", "earth", 3],
  ["氷漬け", "ice", "water", 3],
  ["冷蔵", "ice", "neutral", 2],
  ["冷気", "ice", "wind", 3],
  ["熱気", "fire", "wind", 3],
  ["陽炎", "fire", "wind", 3],
  ["地熱", "fire", "earth", 4],
  ["温泉街", "fire", "trade", 3],
  ["湯治", "water", "life", 3],
  ["湯煙", "water", "fire", 2],
  ["湯気", "water", "fire", 2],
  ["湯船", "water", "life", 2],
  ["湯舟", "water", "life", 2],
  ["桶", "water", "earth", 2],
  ["手桶", "water", "life", 1],
  ["柄杓", "water", "craft", 1],
  ["柄杓屋", "trade", "neutral", 2],
  ["水屋", "water", "trade", 2],
  ["井戸端", "water", "neutral", 2],
  ["井桁", "water", "earth", 2],
  ["轆轤", "water", "craft", 2],
  ["釣瓶", "water", "craft", 2],
  ["水桶", "water", "earth", 2],
  ["水甕", "water", "earth", 2],
  ["水瓶", "water", "neutral", 2],
  ["水瓶座", "cosmos", "water", 4],
  ["牡牛座", "cosmos", "life", 4],
  ["獅子座", "cosmos", "hero", 5],
  ["蠍座", "cosmos", "shadow", 4],
  ["射手座", "cosmos", "wind", 5],
  ["山羊座", "cosmos", "earth", 4],
  ["魚座", "cosmos", "water", 4],
  ["黄道", "cosmos", "light", 4],
  ["赤道儀", "cosmos", "mind", 3],
  ["天球儀", "cosmos", "mind", 4],
  ["地球儀", "earth", "mind", 3],
  ["羅針盤針", "wind", "metal", 2],
  ["方位磁針", "wind", "metal", 2],
  ["磁北", "wind", "ice", 2],
  ["真北", "wind", "light", 2],
  ["極星", "cosmos", "ice", 4],
  ["宵星", "cosmos", "light", 3],
  ["明星", "cosmos", "light", 4],
  ["暁星", "cosmos", "light", 4],
  ["昏星", "cosmos", "shadow", 3],
  ["明星草", "nature", "light", 2],
  ["星影", "cosmos", "shadow", 3],
  ["月影", "cosmos", "shadow", 3],
  ["日陰者", "shadow", "neutral", 2],
  ["月見", "cosmos", "neutral", 3],
  ["花見", "nature", "life", 3],
  ["雪見", "ice", "neutral", 3],
  ["雪洞", "ice", "earth", 2],
  ["雪室", "ice", "earth", 3],
  ["雪崩れ", "ice", "earth", 6],
  ["吹雪道", "ice", "wind", 4],
  ["吹雪眼", "ice", "wind", 4],
  ["雪煙", "ice", "wind", 3],
  ["雪煙り", "ice", "wind", 3],
  ["粉雪", "ice", "wind", 2],
  ["細雪", "ice", "wind", 2],
  ["綿雪", "ice", "life", 2],
  ["霰雲", "ice", "water", 3],
  ["雷雲", "thunder", "water", 4],
  ["積乱雲", "thunder", "wind", 4],
  ["層積雲", "wind", "water", 2],
  ["卷雲", "wind", "cosmos", 3],
  ["夜光雲", "cosmos", "ice", 4],
  ["朝雲", "light", "wind", 2],
  ["夕雲", "neutral", "wind", 2],
  ["山嵐", "wind", "nature", 4],
  ["海嵐", "wind", "water", 5],
  ["陸風", "wind", "earth", 3],
  ["海風", "wind", "water", 3],
  ["季節風", "wind", "nature", 3],
  ["貿易風", "wind", "trade", 3],
  ["偏西風", "wind", "neutral", 3],
  ["旋風", "wind", "neutral", 4],
  ["竜巻", "wind", "nature", 6],
  ["土竜巻", "wind", "earth", 5],
  ["水竜巻", "wind", "water", 5],
  ["火柱", "fire", "nature", 5],
  ["火災", "fire", "shadow", 5],
  ["火消し", "fire", "hero", 3],
  ["火消し壺", "fire", "earth", 2],
  ["防火", "fire", "earth", 3],
  ["防火壁", "fire", "earth", 4],
  ["避火", "fire", "mind", 3],
  ["避難", "travel", "neutral", 3],
  ["避難所", "earth", "neutral", 3],
  ["救護", "light", "life", 3],
  ["救急", "light", "life", 3],
  ["治療", "light", "life", 3],
  ["手当", "life", "neutral", 2],
  ["看護", "light", "life", 3],
  ["療養", "life", "earth", 3],
  ["静養", "ice", "life", 3],
  ["養生", "life", "earth", 3],
  ["薬草園", "life", "earth", 3],
  ["薬園", "life", "earth", 3],
  ["毒草", "shadow", "life", 3],
  ["毒菇", "shadow", "life", 3],
  ["毒蛾", "shadow", "life", 3],
  ["毒牙", "shadow", "life", 3],
  ["毒針", "shadow", "life", 3],
  ["蜂", "life", "wind", 2],
  ["蜂窩", "life", "earth", 2],
  ["蜂蜜", "life", "light", 2],
  ["蝋", "life", "neutral", 2],
  ["蜜蝋", "life", "light", 2],
  ["板子", "craft", "earth", 2],
  ["板材", "craft", "earth", 2],
  ["丸太", "nature", "earth", 3],
  ["薪", "nature", "fire", 2],
  ["炭", "fire", "earth", 2],
  ["石炭", "earth", "shadow", 3],
  ["泥炭", "earth", "water", 2],
  ["石灰", "earth", "light", 2],
  ["石膏", "earth", "neutral", 2],
  ["粘土", "earth", "water", 2],
  ["赤土", "earth", "fire", 2],
  ["黒土", "earth", "shadow", 2],
  ["沃土", "earth", "life", 3],
  ["荒地", "earth", "shadow", 3],
  ["不毛", "earth", "shadow", 3],
  ["砂礫", "earth", "neutral", 2],
  ["玉石", "earth", "light", 3],
  ["磁鉄鉱", "earth", "metal", 4],
  ["黄鉄鉱", "earth", "metal", 3],
  ["銀鉱", "metal", "earth", 4],
  ["金鉱", "metal", "earth", 5],
  ["銅山", "metal", "earth", 4],
  ["鉄山", "metal", "earth", 4],
  ["山師", "earth", "craft", 3],
  ["坑夫", "earth", "shadow", 3],
  ["坑道", "earth", "shadow", 4],
  ["竖坑", "earth", "shadow", 4],
  ["斜坑", "earth", "shadow", 3],
  ["坑内", "earth", "shadow", 3],
  ["通風孔", "wind", "earth", 2],
  ["換気口", "wind", "earth", 2],
  ["煙道", "fire", "earth", 3],
  ["竪坑", "earth", "shadow", 4],
  ["竪穴", "earth", "shadow", 3],
  ["横穴", "earth", "shadow", 3],
  ["古墳", "earth", "shadow", 4],
  ["前方後円墳", "earth", "cosmos", 4],
  ["石室", "earth", "shadow", 3],
  ["埴輪", "earth", "neutral", 2],
  ["勾玉", "light", "earth", 3],
  ["鏡玉", "light", "metal", 3],
  ["鉄剣", "metal", "hero", 5],
  ["銅鐸", "metal", "sound", 3],
  ["銅鏡", "metal", "light", 3],
  ["鉄鏡", "metal", "shadow", 3],
  ["神鏡", "light", "metal", 4],
  ["八咫鏡", "light", "cosmos", 7],
  ["草薙剣", "metal", "hero", 8],
  ["天叢雲剣", "metal", "fantasy", 8],
  ["布都御魂", "metal", "hero", 7],
  ["十握剣", "metal", "hero", 7],
  ["天羽々矢", "wind", "hero", 6],
  ["響矢", "sound", "wind", 4],
  ["破魔矢", "light", "wind", 4],
  ["祈祷矢", "light", "wind", 3],
  ["祝矢", "light", "wind", 3],
  ["鏑矢", "metal", "wind", 4],
  ["征矢", "metal", "hero", 4],
  ["矢筒", "wind", "craft", 2],
  ["矢筈", "wind", "craft", 2],
  ["弦", "sound", "neutral", 2],
  ["弓弦", "wind", "metal", 2],
  ["弩弦", "metal", "wind", 3],
  ["弦楽", "sound", "mind", 3],
  ["管弦", "sound", "mind", 4],
  ["吹奏", "sound", "wind", 3],
  ["打楽", "sound", "earth", 3],
  ["編鐘", "sound", "metal", 4],
  ["編磬", "sound", "earth", 4],
  ["太簇", "sound", "mind", 3],
  ["黄鐘", "sound", "cosmos", 4],
  ["律呂", "sound", "cosmos", 3],
  ["音階", "sound", "mind", 2],
  ["半音", "sound", "neutral", 2],
  ["全音", "sound", "neutral", 2],
  ["調律", "sound", "mind", 3],
  ["調弦", "sound", "wind", 2],
  ["走調", "sound", "shadow", 2],
  ["破調", "sound", "shadow", 3],
  ["変調", "sound", "shadow", 3],
  ["転調", "sound", "wind", 3],
  ["移調", "sound", "wind", 2],
  ["即興", "sound", "fire", 3],
  ["即興曲", "sound", "wind", 4],
  ["即興詩", "sound", "mind", 3],
  ["口吟", "sound", "mind", 2],
  ["朗詠", "sound", "light", 3],
  ["朗読", "sound", "mind", 3],
  ["読経", "sound", "light", 3],
  ["経文", "light", "mind", 3],
  ["偈", "light", "mind", 3],
  ["陀羅尼", "light", "sound", 4],
  ["真言", "light", "sound", 4],
  ["護摩", "fire", "light", 4],
  ["護摩壇", "fire", "earth", 4],
  ["護符札", "light", "craft", 2],
  ["御札", "light", "craft", 2],
  ["破魔札", "light", "craft", 2],
  ["牛首紐", "neutral", "earth", 1],
  ["注連縄", "light", "nature", 3],
  ["神木", "light", "life", 4],
  ["神籬", "light", "nature", 3],
  ["磐座", "light", "earth", 3],
  ["磐境", "light", "earth", 3],
  ["神域", "light", "earth", 4],
  ["神域守", "light", "hero", 5],
  ["巫女", "light", "life", 3],
  ["神主", "light", "mind", 3],
  ["禰宜", "light", "neutral", 3],
  ["権禰宜", "light", "neutral", 3],
  ["宮司", "light", "mind", 4],
  ["神官", "light", "mind", 3],
  ["祭司", "light", "mind", 4],
  ["祠", "light", "earth", 3],
  ["祠宮", "light", "earth", 3],
  ["社", "light", "earth", 3],
  ["神社", "light", "earth", 4],
  ["大社", "light", "earth", 5],
  ["末社", "light", "earth", 2],
  ["摂社", "light", "earth", 3],
  ["境外", "neutral", "earth", 2],
  ["鳥居", "light", "earth", 3],
  ["参道", "light", "earth", 3],
  ["手水舎", "water", "light", 2],
  ["拜殿", "light", "earth", 3],
  ["本殿", "light", "earth", 4],
  ["御神体", "light", "cosmos", 6],
  ["神体山", "light", "earth", 5],
  ["霊峰", "light", "earth", 5],
  ["霊山", "light", "earth", 4],
  ["霊泉", "light", "water", 4],
  ["霊水", "light", "water", 4],
  ["御神水", "light", "water", 4],
  ["神饌米", "light", "life", 3],
  ["新嘗", "light", "life", 4],
  ["大嘗祭", "light", "cosmos", 6],
  ["祈年祭", "light", "earth", 4],
  ["例祭", "light", "sound", 3],
  ["神幸", "light", "travel", 4],
  ["神輿", "light", "travel", 4],
  ["御旅所", "light", "travel", 3],
  ["御旅所祭", "light", "sound", 4],
];

const adjectives = [
  ["凛とした", "ice", "hero", 4],
  ["柔らかな", "life", "water", 3],
  ["硬質な", "metal", "earth", 4],
  ["透明な", "light", "water", 3],
  ["不透明な", "shadow", "earth", 3],
  ["鮮やかな", "light", "wind", 4],
  ["褪せた", "shadow", "neutral", 2],
  ["煌びやかな", "light", "sound", 3],
  ["素朴な", "earth", "life", 3],
  ["華やかな", "light", "wind", 4],
  ["慎ましい", "ice", "mind", 3],
  ["粗野な", "earth", "fire", 3],
  ["洗練された", "light", "mind", 4],
  ["未熟な", "neutral", "life", 2],
  ["円熟した", "mind", "earth", 4],
  ["幼い", "life", "neutral", 2],
  ["老いた", "earth", "shadow", 3],
  ["若々しい", "life", "wind", 3],
  ["古めかしい", "earth", "shadow", 3],
  ["新しげな", "light", "wind", 3],
  ["頼もしい", "hero", "earth", 4],
  ["頼りない", "wind", "shadow", 2],
  ["頼りがいのある", "hero", "earth", 4],
  ["心強い", "hero", "light", 4],
  ["心細い", "shadow", "wind", 2],
  ["心憎い", "shadow", "fire", 3],
  ["憎らしい", "shadow", "fire", 3],
  ["愛おしい", "light", "life", 3],
  ["懐かしい", "mind", "earth", 3],
  ["名残惜しい", "water", "mind", 3],
  ["惜しげもない", "fire", "neutral", 3],
  ["惜しみない", "light", "hero", 4],
  ["惜しみ深い", "mind", "earth", 3],
  ["計り知れない", "cosmos", "mind", 5],
  ["測り知れない", "cosmos", "mind", 5],
  ["底知れない", "shadow", "water", 4],
  ["底無しの", "shadow", "water", 4],
  ["際限ない", "wind", "neutral", 3],
  ["終わりなき", "cosmos", "neutral", 4],
  ["終わりある", "earth", "neutral", 3],
  ["限りある", "earth", "neutral", 3],
  ["限りない", "cosmos", "wind", 4],
  ["無限の", "cosmos", "light", 5],
  ["有限の", "mind", "earth", 3],
  ["不滅の", "light", "cosmos", 6],
  ["脆弱な", "ice", "shadow", 3],
  ["強靭な", "earth", "hero", 5],
  ["頑丈な", "earth", "metal", 4],
  ["華奢な", "wind", "light", 2],
  ["逞しい", "hero", "earth", 4],
  ["細い", "wind", "neutral", 2],
  ["太い", "earth", "neutral", 2],
  ["長い", "wind", "neutral", 2],
  ["短い", "fire", "neutral", 2],
  ["高い", "wind", "light", 3],
  ["低い", "earth", "shadow", 2],
  ["深い", "water", "shadow", 4],
  ["浅い", "water", "neutral", 2],
  ["重い", "earth", "metal", 4],
  ["軽い", "wind", "neutral", 2],
  ["速い", "wind", "fire", 4],
  ["遅い", "earth", "ice", 2],
  ["鋭い", "metal", "wind", 4],
  ["鈍い", "earth", "neutral", 2],
  ["明るい", "light", "wind", 3],
  ["暗い", "shadow", "neutral", 3],
  ["眩しい", "light", "fire", 4],
  ["淡い", "water", "light", 2],
  ["濃い", "shadow", "earth", 3],
  ["薄い", "ice", "neutral", 2],
  ["厚い", "earth", "neutral", 3],
  ["薄らい", "ice", "wind", 2],
  ["仄暗い", "shadow", "earth", 3],
  ["仄かな", "shadow", "neutral", 3],
  ["微かな", "wind", "neutral", 2],
  ["著しい", "fire", "light", 4],
  ["著大な", "earth", "hero", 5],
  ["微小な", "ice", "neutral", 2],
  ["巨大な", "earth", "fantasy", 6],
  ["極大の", "cosmos", "earth", 6],
  ["極小の", "ice", "cosmos", 3],
];

const conjs = [
  ["または", "link", "neutral"],
  ["もしくは", "link", "neutral"],
  ["さらに", "link", "fire"],
  ["しかも", "link", "mind"],
  ["それどころか", "link", "shadow"],
  ["それどころではなく", "link", "shadow"],
  ["つまり", "link", "mind"],
  ["ところが", "link", "shadow"],
  ["ところで", "link", "neutral"],
  ["とにかく", "link", "fire"],
  ["なぜなら", "link", "cosmos"],
  ["なぜなれば", "link", "cosmos"],
  ["ゆえに", "link", "fire"],
  ["それゆえ", "link", "fire"],
  ["したがって", "link", "earth"],
  ["そこで", "link", "neutral"],
  ["では", "link", "neutral"],
  ["ではなく", "link", "shadow"],
  ["ではあるが", "link", "neutral"],
  ["ものの", "link", "shadow"],
  ["けれども", "link", "shadow"],
  ["のに", "link", "shadow"],
  ["ので", "link", "neutral"],
  ["からして", "link", "earth"],
  ["にしても", "link", "neutral"],
  ["にせよ", "link", "neutral"],
  ["にしろ", "link", "neutral"],
  ["といっても", "link", "neutral"],
  ["というより", "link", "mind"],
  ["というか", "link", "sound"],
  ["なお", "link", "neutral"],
  ["またしても", "link", "shadow"],
  ["かつて", "link", "cosmos"],
  ["いまだ", "link", "ice"],
  ["すでに", "link", "earth"],
  ["まだ", "link", "wind"],
  ["すぐに", "link", "wind"],
  ["やがて", "link", "cosmos"],
  ["ついに", "link", "fire"],
  ["とうとう", "link", "neutral"],
  ["いっそ", "link", "fire"],
  ["むしろ", "link", "mind"],
  ["かえって", "link", "wind"],
  ["一方で", "link", "water"],
  ["他方", "link", "neutral"],
];

const particles = [
  ["は", "link", "neutral"],
  ["も", "link", "neutral"],
  ["に", "link", "neutral"],
  ["へ", "link", "neutral"],
  ["まで", "link", "neutral"],
  ["から", "link", "neutral"],
  ["より", "link", "neutral"],
  ["ばかり", "link", "neutral"],
  ["ほど", "link", "neutral"],
  ["だけ", "link", "neutral"],
  ["こそ", "link", "neutral"],
  ["でも", "link", "neutral"],
  ["など", "link", "neutral"],
  ["か", "link", "neutral"],
];

const wordsPath = path.join(__dirname, "..", "js", "words.js");
let src = fs.readFileSync(wordsPath, "utf8");

/** @param {string} catalogSrc */
function collectExistingTexts(catalogSrc) {
  const set = new Set();
  for (const m of catalogSrc.matchAll(/text: "([^"]*)"/g)) {
    set.add(m[1]);
  }
  return set;
}

const existingTexts = collectExistingTexts(src);
const NEED = 500 - 242 + 1;

function pushLines(list, kind, slotMask, out, nextId) {
  const seenLocal = new Set();
  for (const row of list) {
    if (out.length >= NEED) break;
    const text = row[0];
    if (seenLocal.has(text) || existingTexts.has(text)) continue;
    seenLocal.add(text);
    existingTexts.add(text);
    const power = kind === "particle" ? 0 : kind === "conj" ? 1 : row[3];
    const tags = [row[1], row[2]];
    const p = kind === "adj_na" ? row[3] : power;
    out.push(
      `  { id: "w${String(nextId).padStart(3, "0")}", text: ${JSON.stringify(text)}, kind: "${kind}", tags: ${JSON.stringify(tags)}, power: ${p}, slotMask: ${slotMask} },`
    );
    nextId++;
  }
  return nextId;
}

const out = [];
let nid = 242;
nid = pushLines(nouns, "noun", 7, out, nid);
nid = pushLines(adjectives, "adj_na", 4, out, nid);
nid = pushLines(conjs, "conj", 7, out, nid);
nid = pushLines(particles, "particle", 7, out, nid);

const endId = nid - 1;
if (out.length !== NEED || endId !== 500) {
  console.error("expected exactly", NEED, "new entries ending w500; got", out.length, "ending w" + String(endId).padStart(3, "0"));
  process.exit(1);
}

const needle =
  '  { id: "w241", text: "や", kind: "particle", tags: ["link", "neutral"], power: 0, slotMask: 7 },';
const idx241 = src.lastIndexOf(needle);
if (idx241 < 0) {
  console.error("w241 anchor line not found");
  process.exit(1);
}
let pos = idx241 + needle.length;
if (src[pos] === "\r") pos++;
if (src[pos] === "\n") pos++;
if (src.slice(pos, pos + 2) !== "];") {
  console.error("expected ]; immediately after w241 — file may already be patched");
  process.exit(1);
}
const nl = src.includes("\r\n") ? "\r\n" : "\n";
src = src.slice(0, pos) + out.join(nl) + nl + src.slice(pos);
fs.writeFileSync(wordsPath, src, "utf8");
console.error("patched words.js: w242–w500 (", NEED, "entries)");
